### PR TITLE
Add Travis-CI integration Fix #18

### LINKED ISSUE #18: Integrate with Travis-CI
There are build failures on pull requests as the .travis.yml file cannot be found in root.

### PR DESCRIPTION
**Pull request by Janakshi28**
The added .travis.yml file contains the basic configurations for the programming language, Noje.js versions and for the infrastructure. This Fixes issue #18 .

### CODE REVIEW

**Comment by rajikaimal** [comment]
Can you add `npm test` command to `.travis.yml`. If npm test fails, maybe you can take this [issue](https://github.com/99xt/react-boilerplate/issues/11) as well

**Comment by Janakshi28** [comment]
Sure. I'll add it :)

**Comment by rajikaimal** [comment]
Great

**Comment by rajikaimal** [comment]
@charithsoori Need a review

**Comment by charithsoori** [comment]
Good stuff.

**Pull request merged**
