### PR TITLE
Add the CODE_OF_CONDUCT.md Fix #16

### LINKED ISSUE #16: Add CODE_OF_CONDUCT.md
Add CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by Janakshi28**

### CODE REVIEW

**Comment by charithsoori** [comment]
Build failed. Please check the Travis log

**Comment by rajikaimal** [comment]
[Travis config](https://travis-ci.org/99xt/react-boilerplate/jobs/267096781/config) is for Ruby which should be Node.

**Comment by rehrumesh** [comment]
I checked the travis yml. It has correct configurations. However Travis worker unable to detect the .travis.yml for some reason. That is why it fallback to default yml(which is Ruby)

**Comment by rehrumesh** [comment]
@Janakshi28 can you sync the branch with current master. Apparently when you started working in the branch, `.travis.yml` was missing in the branch. Which is why the error occurs. After you sync with master, it should be solved.

**Comment by rajikaimal** [comment]
Same issue with #21. Need to sync with `master`

**Comment by Janakshi28** [comment]
Yeah, I worked on issue #18 and before it gets merged I started working on this issue, syncing with master, because by then master branch didn't have a .travis.yml file.  I think that's why we are getting this buid failure. I'll sync the master as you suggested.

**Comment by Janakshi28** [comment]
@rehrumesh and @rajikaimal , I think now it's fine.

**Comment by rajikaimal** [comment]
Yup, this looks good now @charithsoori

**Pull request merged**
